baseURL: "https://somethingstochastic.com/"
title: "Something Stochastic"
languageCode: "en-uk"

params:
  logo: static/img/stochastic-logo.png
  author: Dominik Kiersz
  custom_css: static/css/main.css
