baseURL: 'https://somethingstochastic.com/'
title: 'Something Stochastic'
languageCode: 'en-uk'

params:
  author: 'Dominik Kiersz; Bethan Iley'
  description: 'Good, occassionally poor'
  avatar: static/images/stochastic-logo.png

