baseURL: "//somethingstochastic.com/"
title: "Something Stochastic"
languageCode: "en-uk"
custom_css: css/custom.css

params:
  author: Dominik Kiersz

taxonomies:
  tag: "tags"
  category: "categories"

module:
  mounts:
    - source: node_modules/bootstrap/scss
      target: assets/scss/bootstrap
    - source: node_modules/bootstrap/dist/js/bootstrap.min.js
      target: assets/js/bootstrap.min.js
