name: Deploy Blog

on:
  push:
    branches:
      - production

permissions:
  contents: read

jobs:
  build:
    name: "Build Blog"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Read Hugo Version
        id: hugo-version
        run: |
          . ./.env
          echo "::set-output name=HUGO_VERSION::${HUGO_VERSION}"
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "${{ steps.hugo-version.outputs.HUGO_VERSION }}"
          extended: true
      - name: Build Hugo Site
        run: |
          cd src
          hugo --minify
  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    steps:
      - name: Deploy to Azure Static Web Apps
        uses: static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/src"
          api_location: "api"
          output_location: "/src/public"
#https://learn.microsoft.com/en-gb/azure/static-web-apps/build-configuration?tabs=github-actions
#https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-azure/deploying-to-azure-static-web-app
