name: Deploy Blog

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

permissions:
  contents: read

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.92.2
          extended: true
      - name: Build Hugo Site
        run: |
          cd src
          hugo --minify
        continue-on-error: false
      - uses: actions/upload-artifact@v3
        with:
          name: something-stockastic-build
          path: src/public
        continue-on-error: false
  deploy:
    name: "Deploy"
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: something-stockastic-build
          path: /public
      - run: ls -la
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/public"
          api_location: "api"
          output_location: ""
          skip_app_build: true
