name: Deploy Infrastructure

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  infra:
    name: "Something Stockastic Infra"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Terraform Init
        run: |
          cd infra
          terraform init
      - name: Terraform Plan
        run: |
          cd infra
          terraform plan -out=plan.out
      - name: Terraform Apply
        run: |
          cd infra
          terraform apply plan.out
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
