name: Infrastructure Deployment

on:
  push:
    branches:
      - production

jobs:
  infra:
    name: Deploy - Infrastructure
    runs-on: ubuntu-22.04
    env:
      # SPN credentials
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    # Use the Bash shell regardless whether the Windows runner is selected
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Format
        run: |
          terraform fmt -check
        working-directory: infra
      - name: Terraform Init
        run: |
          terraform init
        working-directory: infra
      - name: Terraform Validate
        run: |
          terraform validate
        working-directory: infra
      - name: Terraform Plan
        run: |
          terraform plan -out=plan.out
        working-directory: infra
      - name: Terraform Apply
        run: |
          terraform apply plan.out
        working-directory: infra
